module "vpc" {
    source = "terraform-aws-modules/vpc/aws"
    version = "6.6.1"
    name = var.vpc_name
    cidr = var.vpc_cidr
    azs = var.availability_zones
    public_subnets = var.public_subnets
    private_subnets = var.private_subnets
    database_subnets = var.database_subnets
    enable_dns_hostnames = true
    enable_dns_support = true
    enable_nat_gateway = var.enable_nat_gateway
    single_nat_gateway = var.single_nat_gateway
    one_nat_gateway_per_az = var.one_nat_gateway_per_az
    create_database_subnet_group = var.create_database_subnet_group
    manage_default_security_group = var.manage_default_security_group
    manage_default_network_acl = var.manage_default_network_acl
    manage_default_route_table = var.manage_default_route_table
    enable_vpn_gateway = var.enable_vpn_gateway
    tags = var.tags
}